cod = str(input("Digite uma frase:"))
from string import *
print(cod.replace(' ', '-'))
print(cod.count('a'))
print(cod.find('gab'))
print(cod.split())
print(cod.upper())
print(cod.lower())
print(cod.isupper())
print(cod.islower())
print(cod.isalpha())
print(cod.isalnum())
print(cod.isdigit())
print(cod.isspace())